### ISSUE TITLE
May I make a pull request to add unpresented papers?

### ISSUE THREAD

**Issue by ntvy95** [gjy3035/Awesome-Crowd-Counting#2]
Thank you very much for your great work.

I am opening this issue to inquire about the possibility of add unpresented papers and edit some misinfo (such as Single-Image Crowd Counting via Multi-Column Convolutional Neural Network has no official code).

May I do that?

**Comment by gjy3035** [comment]
Welcome! Thanks for your help!
For the missinfo unpresented (accpted or published) papers in this repo, I am glad to accept PR to imporove this repo.
Furthermore, as for the unpublished papers, I still think we should only add some arXiv papers. Otherwise, the copyright can be infringed.  And I think it is necessary to add a new section to record the unpublished papers.

Cheers!

**Comment by ntvy95** [comment]
Thank you for your approval. I made a pull request. Please tell me if there are any problems regarding my pull request.

I think the difference between arXiv papers and traditionally published papers is that arXiv papers can have multiple versions over years so I specified the years of its first version and last version.

**Comment by ntvy95** [comment]
Hi @gjy3035 , thank you for your feedback. I have made several pull requests but I was not sure why they disappeared after a short period of time. Maybe I had done something wrong back then. Now I make a new test pull request, please check if it works. Thank you.

**Comment by gjy3035** [comment]
@ntvy95 Thanks a lot!
